### ISSUE TITLE
stuck on patching Vac3 

### ISSUE THREAD

**Issue by ducky0** [leo4048111/Potato-Injector#5]

**Comment by leo4048111** [comment]
Im currently working on class projects and haven't been maintaining this injector for months so the patching method might be out of date, feel free to make a PR if u manage to solve this problem.

**Comment by leo4048111** [comment]
BTW i just tested the release build on jul 1 on my PC, which is running windows 11 os and the patching works fine. I guess it's ur environment issue.

**Comment by leo4048111** [comment]
BTW i just executed the jul 1 release build binary on my PC, which is running windows 11 os and the patching works fine. I guess it's ur environment issue.

**Comment by ducky0** [comment]
what do u use for the "constexpr BYTE vac3_data[135680]" byte stuff? i wanna see if i need to update it or try a diff vac3_inhibitor

**Comment by ducky0** [comment]
is it just the dll converted to bytes?

**Comment by leo4048111** [comment]
yes.
