### ISSUE TITLE
d3dx9.h missing

### ISSUE THREAD

**Issue by mildnsj** [leo4048111/Potato-Injector#6]
Just can't find a way to solve it, WIN11, directx12 installed, cant find a path for directx, and none of the commands or changing VC++ directories work.

**Comment by leo4048111** [comment]
Have you installed [DirectX Software Development Kit](https://www.microsoft.com/en-us/download/details.aspx?id=6812) and set environment variable `DXSDK_DIR` to its installation directory?

**Comment by mildnsj** [comment]
Fixed, I don't know what the f**k was my computer doing, I switched to c++20 and then switch back and it all worked fine.
IDK wtf happend
